######################################################################
# Automatically generated by qmake (3.0) Fri Sep 8 15:00:43 2017
######################################################################

TEMPLATE = app
TARGET = carlife_test

DESTDIR = bin
RCC_DIR += tmp
MOC_DIR += tmp
OBJECTS_DIR += tmp

#debug C++
QMAKE_CXXFLAGS += -g

#qt
QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

#carlife source
INCLUDEPATH += /home/imx6-solo/sdk/carlife/include

#carlife sdk
INCLUDEPATH += ./carlife_sdk

#carlife common
INCLUDEPATH += ./carlife_common

#carlife modules
INCLUDEPATH += ./carlife_modules/session_mgr \
               ./carlife_modules/screen_service \
               ./carlife_modules/media_service \
               ./carlife_modules/navi_service \
               ./carlife_modules/vr_service \
               ./carlife_modules/tel_service \
               ./carlife_modules/input_service

#pthread
LIBS += -lpthread

#protobuf
LIBS += -L/home/imx6-solo/sdk/protobuf-install/lib -lprotobuf

#carlife
LIBS += -L/home/imx6-solo/sdk/carlife/lib -lcarlifevehicle

# Input
SOURCES += \
    carlife_sdk/CarlifeSdk.cpp \
    carlife_manager/CarlifeMgr.cpp \
    carlife_modules/session_mgr/SessionMgr.cpp \
    carlife_modules/screen_service/ScreenService.cpp \
    carlife_modules/vr_service/VrService.cpp \
    carlife_modules/navi_service/NaviService.cpp \
    carlife_modules/input_service/InputService.cpp \
    carlife_modules/tel_service/TelService.cpp \
    carlife_modules/media_service/MediaService.cpp \
    carlife_test/main.cpp \
    carlife_test/mainwindow.cpp

HEADERS += \
    carlife_common/CarlifeCommon.h \
    carlife_sdk/CarlifeSdk.h \
    carlife_manager/CarlifeMgr.h \
    carlife_modules/session_mgr/SessionMgr.h \
    carlife_modules/screen_service/ScreenService.h \
    carlife_modules/vr_service/VrService.h \
    carlife_modules/navi_service/NaviService.h \
    carlife_modules/input_service/InputService.h \
    carlife_modules/tel_service/TelService.h \
    carlife_modules/media_service/MediaService.h \
    carlife_test/mainwindow.h
